### ISSUE TITLE
server crash (keeps crashing)

### ISSUE THREAD

**Issue by rberiot** [gdesmott/karapulse#22]
[2019-03-06T14:37:57Z INFO  rocket::rocket] GET /api/status/ application/json:
[2019-03-06T14:38:00Z INFO  rocket::rocket] GET /api/enqueue_db/77651/JZOGEOHGEO application/json:
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
karapulse: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)

**Comment by gdesmott** [comment]
I just merged my patch which should fix that. Can you retry?

**Comment by gdesmott** [comment]
Should be ok now with https://github.com/gdesmott/karapulse/commit/478ee09adb5b1548ab72faf3df438badb7b655f3
